[package]
name = "dotfile-manager"
version = "0.1.0"
edition = "2024"

[lints.clippy]
correctness = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
mod_module_files = "forbid"


[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.34", features = ["cargo", "derive"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
toml = "0.8.20"
