[package]
name = "mac"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
cmd_lib = { workspace = true }
core = { path = "../core" }
serde = { workspace = true }
tracing = { workspace = true }
