[package]
name = "core"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.97"
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.140"
serde_yml = "0.0.12"
shellexpand = "3.1.0"
toml = "0.8.20"
