# nvim = "git@github.com:Sironheart/neovim-config.git"
nvim = "https://github.com/Sironheart/neovim-config.git"

[base]
basePath = "~/projects"
useGitSourcePath = true

[[files]]
path = "~/.ssh/config"
content = """
Include ~/.orbstack/ssh/config

#Host *
#	IdentityAgent ~/.1password/agent.sock

Host *
	IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
	ServerAliveInterval 3600
	SetEnv TERM=xterm-256color
"""
